name: "Test SAR CPU Data Analyzer Action"

on: [push, pull_request]

jobs:
  test-analyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SAR CPU Data Analyzer
        uses: ./
        with:
          log-file: "./sample/cpu.log"
          test-file: "./sample/sample-test.json"
          output-file: "./test-results.json" 
          html-report: "./test-report.html"
      
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
