name: "Test SAR CPU Data Analyzer Action"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest

  analyze:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SAR CPU Data Analyzer
        uses: ./
        with:
          log-file: "./sample/cpu.log"
          test-file: "./sample/sample-test.json"
          output-file: "./test-results.json" 
          html-report: "./test-report.html"
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json
          if-no-files-found: error
      
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report.html
          if-no-files-found: error
